name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ 'rc-*' , 'master' ]

jobs:
  native:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.3'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make

      - name: test
        run: make test 0

  device:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: platformio
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: build
        run: make test-esp32
